In [ ]:
#Null : PGA has no effect on winning, so the win rate of the higher PGA team should be around 50%.
#Alt :  Higher PGA teams should win significantly more than 50% of the time.

#test statistic : # games won by team with higher PGA / total number of games

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("transformed_league_data.csv")

In [4]:
df.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,gameid,side,pick1,pick2,pick3,pick4,pick5,ban1,ban2,ban3,ban4,ban5,result,num_counters,num_counters_banned,PGA
0,0,0,0,FRA1TMNT1/450135,Blue,Rumble,Jarvan IV,Syndra,Sivir,Annie,Alistar,Azir,Irelia,NaN,NaN,0,0,1,1
1,1,1,1,FRA1TMNT1/450135,Red,Gnar,Rengar,Ahri,Graves,Janna,Rek'Sai,LeBlanc,Kassadin,NaN,NaN,1,0,1,1
2,2,2,2,FRA1TMNT1/450138,Blue,Lissandra,Rek'Sai,Xerath,Tristana,Janna,LeBlanc,Kassadin,Lee Sin,NaN,NaN,1,0,0,0
3,3,3,3,FRA1TMNT1/450138,Red,Rumble,Rengar,Syndra,Sivir,Annie,Gnar,Azir,Irelia,NaN,NaN,0,2,1,3
4,4,4,4,FRA1TMNT1/450168,Blue,Gnar,Lee Sin,Nidalee,Corki,Janna,Cassiopeia,Rek'Sai,Lissandra,NaN,NaN,1,0,0,0